### ISSUE TITLE
Crash ios 11 

### ISSUE THREAD

**Issue by AfrozZaheer** [Hardtack/HTProgressHUD#16]
![screen shot 2017-10-02 at 5 19 18 pm](https://user-images.githubusercontent.com/25176835/31076881-d9d709ba-a795-11e7-9e4c-fc9fa0c127ff.png)

**Comment by AfrozZaheer** [comment]
issue is at line 242 can you fix it ASAP?

**Comment by Hardtack** [comment]
I'm sorry to say that I can't.
As you can see in [README.md](https://github.com/Hardtack/HTProgressHUD/blob/master/README.md), I don't intend to maintain this project.
It passed too much time when I came back from military service, and it have been too outdated.
